### ISSUE TITLE
New 0.2.0 release fail tests

### ISSUE THREAD

**Issue by mugami-ast** [LearnBoost/up#34]
```
$ git describe --tags
0.2.0
$ make test

  ......

  ✖ 1 of 9 tests failed:

  1) up should suicide workers if master dies:
     Error: expected true to equal false
      at Assertion.assert (.../up/node_modules/expect.js/expect.js:99:13)
      at Assertion.equal (.../up/node_modules/expect.js/expect.js:200:10)
      at Assertion.be (.../up/node_modules/expect.js/expect.js:73:24)
      at Object._onTimeout (.../up/test/up.js:171:33)
      at Timer.ontimeout (timers.js:94:19)


make: *** [test] Error 1
```

When running on pull request #30 it passes.

```
$ git describe --tags
0.2.0-3-ga8e8560
$ make test

  .........

  ✔ 9 tests complete (1621ms)
```

**Comment by mugami-ast** [comment]
Fixed by merging #30 and releasing 0.2.1
